name: iOS Tests

on:
  pull_request:
    branches: 
      - develop
      - main
      - 'feature/**'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:

    runs-on: macOS-latest

    steps:
    - uses: actions/checkout@v1
    
    - name: Run unit tests in data layer
      run: xcodebuild -project 'RickAndMorty/R&M.xcodeproj' -scheme 'InfraTests' test CODE_SIGNING_ALLOWED=NO
   
    - name: Run unit tests in data layer
      run: xcodebuild -project 'RickAndMorty/R&M.xcodeproj' -scheme 'DataTests' test CODE_SIGNING_ALLOWED=NO
    
    - name: Run unit tests in data layer
      run: xcodebuild -project 'RickAndMorty/R&M.xcodeproj' -scheme 'PresentationTests' test CODE_SIGNING_ALLOWED=NO
